---
'8':
  fullname: 'Rocky Linux 8'
  revision: '8.6'
  rclvl: 'RC2'
  major: '8'
  minor: '6'
  profile: '8'
  bugurl: 'https://bugs.rockylinux.org'
  allowed_arches:
    - x86_64
    - aarch64
  provide_multilib: False
  project_id: ''
  repo_symlinks:
    devel: 'Devel'
    NFV: 'nfv'
  renames: {}
  all_repos:
    - 'BaseOS'
    - 'AppStream'
    - 'PowerTools'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
    - 'extras'
    - 'devel'
    - 'plus'
    - 'rockyrpi'
  no_comps_or_groups:
    - 'extras'
    - 'devel'
    - 'plus'
    - 'rockyrpi'
  comps_or_groups:
    - 'BaseOS'
    - 'AppStream'
    - 'PowerTools'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
  has_modules:
    - 'AppStream'
    - 'PowerTools'
  structure:
    packages: 'os/Packages'
    repodata: 'os/repodata'
  iso_map:
    xorrisofs: False
    iso_level: False
    images:
      dvd:
        disc: True
        variant: 'AppStream'
        repos:
          - 'BaseOS'
          - 'AppStream'
      minimal:
        disc: True
        isoskip: True
        repos:
          - 'minimal'
        variant: 'minimal'
      BaseOS:
        disc: False
        isoskip: True
        variant: 'BaseOS'
        repos:
          - 'BaseOS'
          - 'AppStream'
    lorax:
      repos:
        - 'BaseOS'
        - 'AppStream'
      variant: 'BaseOS'
      lorax_removes:
        - 'libreport-rhel-anaconda-bugzilla'
      required_pkgs:
        - 'lorax'
        - 'genisoimage'
        - 'isomd5sum'
        - 'lorax-templates-rhel'
        - 'lorax-templates-generic'
        - 'xorriso'
  cloudimages:
    images:
      - EC2
      - GenericCloud
    formats:
      - qcow2
      - raw
  livemap:
    git_repo: 'https://git.resf.org/sig_core/kickstarts.git'
    branch: 'r9'
    ksentry:
      Workstation: rocky-live-workstation.ks
      Workstation-Lite: rocky-live-workstation-lite.ks
      XFCE: rocky-live-xfce.ks
      KDE: rocky-live-kde.ks
    allowed_arches:
      - x86_64
    required_pkgs:
      - 'lorax-lmc-novirt'
      - 'vim-minimal'
      - 'pykickstart'
      - 'git'
  repoclosure_map:
    arches:
      x86_64: '--forcearch=x86_64 --arch=x86_64 --arch=athlon --arch=i686 --arch=i586 --arch=i486 --arch=i386 --arch=noarch'
      aarch64: '--forcearch=aarch64 --arch=aarch64 --arch=noarch'
      ppc64le: '--forcearch=ppc64le --arch=ppc64le --arch=noarch'
      s390x: '--forcearch=s390x --arch=s390x --arch=noarch'
    repos:
      BaseOS: []
      AppStream:
        - BaseOS
      PowerTools:
        - BaseOS
        - AppStream
      HighAvailability:
        - BaseOS
        - AppStream
      ResilientStorage:
        - BaseOS
        - AppStream
      RT:
        - BaseOS
        - AppStream
      NFV:
        - BaseOS
        - AppStream
  extra_files:
    git_repo: 'https://git.rockylinux.org/staging/src/rocky-release.git'
    git_raw_path: 'https://git.rockylinux.org/staging/src/rocky-release/-/raw/r8/'
    branch: 'r8'
    gpg:
      stable: 'SOURCES/RPM-GPG-KEY-rockyofficial'
      testing: 'SOURCES/RPM-GPG-KEY-rockytesting'
    list:
      - 'SOURCES/COMMUNITY-CHARTER'
      - 'SOURCES/EULA'
      - 'SOURCES/LICENSE'
      - 'SOURCES/RPM-GPG-KEY-rockyofficial'
      - 'SOURCES/RPM-GPG-KEY-rockytesting'
...
