---
'9-lookahead':
  fullname: 'Rocky Linux 9.1'
  revision: '9.1'
  rclvl: 'LH1'
  major: '9'
  minor: '1'
  profile: '9-lookahead'
  bugurl: 'https://bugs.rockylinux.org'
  checksum: 'sha256'
  allowed_arches:
    - x86_64
    - aarch64
    - ppc64le
    - s390x
  provide_multilib: True
  project_id: ''
  repo_symlinks:
    NFV: 'nfv'
  renames:
    all: 'devel'
  all_repos:
    - 'all'
    - 'BaseOS'
    - 'AppStream'
    - 'CRB'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
    - 'SAP'
    - 'SAPHANA'
    - 'extras'
    - 'plus'
  structure:
    packages: 'os/Packages'
    repodata: 'os/repodata'
  iso_map:
    xorrisofs: True
    iso_level: False
    images:
      dvd:
        disc: True
        variant: 'AppStream'
        repos:
          - 'BaseOS'
          - 'AppStream'
      minimal:
        disc: True
        isoskip: True
        repos:
          - 'minimal'
          - 'BaseOS'
        variant: 'minimal'
      BaseOS:
        disc: False
        isoskip: True
        variant: 'BaseOS'
        repos:
          - 'BaseOS'
          - 'AppStream'
    lorax:
      repos:
        - 'BaseOS'
        - 'AppStream'
      variant: 'BaseOS'
      lorax_removes:
        - 'libreport-rhel-anaconda-bugzilla'
      required_pkgs:
        - 'lorax'
        - 'genisoimage'
        - 'isomd5sum'
        - 'lorax-templates-rhel'
        - 'lorax-templates-generic'
        - 'xorriso'
  cloudimages:
    images:
      EC2:
        format: raw
      GenericCloud:
        format: qcow2
  livemap:
    git_repo: 'https://git.resf.org/sig_core/kickstarts.git'
    branch: 'r9lh'
    ksentry:
      Workstation: rocky-live-workstation.ks
      Workstation-Lite: rocky-live-workstation-lite.ks
      XFCE: rocky-live-xfce.ks
      KDE: rocky-live-kde.ks
    allowed_arches:
      - x86_64
    required_pkgs:
      - 'lorax-lmc-novirt'
      - 'vim-minimal'
      - 'pykickstart'
      - 'git'
  variantmap:
    git_repo: 'https://git.rockylinux.org/rocky/pungi-rocky.git'
    branch: 'r9lh'
    git_raw_path: 'https://git.rockylinux.org/rocky/pungi-rocky/-/raw/r9lh/'
  repoclosure_map:
    arches:
      x86_64: '--forcearch=x86_64 --arch=x86_64 --arch=athlon --arch=i686 --arch=i586 --arch=i486 --arch=i386 --arch=noarch'
      aarch64: '--forcearch=aarch64 --arch=aarch64 --arch=noarch'
      ppc64le: '--forcearch=ppc64le --arch=ppc64le --arch=noarch'
      s390x: '--forcearch=s390x --arch=s390x --arch=noarch'
    repos:
      devel: []
      BaseOS: []
      AppStream:
        - BaseOS
      CRB:
        - BaseOS
        - AppStream
      HighAvailability:
        - BaseOS
        - AppStream
      ResilientStorage:
        - BaseOS
        - AppStream
      RT:
        - BaseOS
        - AppStream
      NFV:
        - BaseOS
        - AppStream
      SAP:
        - BaseOS
        - AppStream
        - HighAvailability
      SAPHANA:
        - BaseOS
        - AppStream
        - HighAvailability
  extra_files:
    git_repo: 'https://git.rockylinux.org/staging/src/rocky-release.git'
    git_raw_path: 'https://git.rockylinux.org/staging/src/rocky-release/-/raw/r9/'
    branch: 'r9lh'
    gpg:
      stable: 'SOURCES/RPM-GPG-KEY-Rocky-9'
      testing: 'SOURCES/RPM-GPG-KEY-Rocky-9-Testing'
    list:
      - 'SOURCES/Contributors'
      - 'SOURCES/COMMUNITY-CHARTER'
      - 'SOURCES/EULA'
      - 'SOURCES/LICENSE'
      - 'SOURCES/RPM-GPG-KEY-Rocky-9'
      - 'SOURCES/RPM-GPG-KEY-Rocky-9-Testing'
...
