---
name: Build empanada container images

on:
  push:
    branches: [ $default-branch, "devel" ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  buildx:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
          context: ./iso/empanadas
          file: ./iso/empanadas/Containerfile.imagefactory
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/rocky-linux/empanadas-imagefactory:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
